import visualize
# not real testing okay, cba to do that.
# just a helper to analyse certain issues
def testSteering():
    print("=== Steering test ===")
    print(visualize._visSteering(1.0) + " 1.0")
    print(visualize._visSteering(0.9) + " 0.9")
    print(visualize._visSteering(0.8) + " 0.8")
    print(visualize._visSteering(0.7) + " 0.7")
    print(visualize._visSteering(0.6) + " 0.6")
    print(visualize._visSteering(0.5) + " 0.5")
    print(visualize._visSteering(0.4) + " 0.4")
    print(visualize._visSteering(0.3) + " 0.3")
    print(visualize._visSteering(0.2) + " 0.2")
    print(visualize._visSteering(0.1) + " 0.1")
    print(visualize._visSteering(0.0) + " 0.0")
    print(visualize._visSteering(-0.0) + " -0.0")
    print(visualize._visSteering(-0.1) + " -0.1")
    print(visualize._visSteering(-0.2) + " -0.2")
    print(visualize._visSteering(-0.3) + " -0.3")
    print(visualize._visSteering(-0.4) + " -0.4")
    print(visualize._visSteering(-0.5) + " -0.5")
    print(visualize._visSteering(-0.6) + " -0.6")
    print(visualize._visSteering(-0.7) + " -0.7")
    print(visualize._visSteering(-0.8) + " -0.8")
    print(visualize._visSteering(-0.9) + " -0.9")
    print(visualize._visSteering(-1.0) + " -1.0")
    print("=== Steering test part 2===")
    print(visualize._visSteering(-0.01) + " -0.01")
    print(visualize._visSteering(-0.11) + " -0.11")
    print(visualize._visSteering(-0.21) + " -0.21")
    print(visualize._visSteering(-0.31) + " -0.31")
    print(visualize._visSteering(-0.41) + " -0.41")
    print(visualize._visSteering(-0.51) + " -0.51")
    print(visualize._visSteering(-0.61) + " -0.61")
    print(visualize._visSteering(-0.71) + " -0.71")
    print(visualize._visSteering(-0.81) + " -0.81")
    print(visualize._visSteering(-0.91) + " -0.91")
    print(visualize._visSteering(-0.99) + " -0.99")
    print(visualize._visSteering(0.01) + " 0.01")
    print(visualize._visSteering(0.11) + " 0.11")
    print(visualize._visSteering(0.21) + " 0.21")
    print(visualize._visSteering(0.31) + " 0.31")
    print(visualize._visSteering(0.41) + " 0.41")
    print(visualize._visSteering(0.51) + " 0.51")
    print(visualize._visSteering(0.61) + " 0.61")
    print(visualize._visSteering(0.71) + " 0.71")
    print(visualize._visSteering(0.81) + " 0.81")
    print(visualize._visSteering(0.91) + " 0.91")
    print(visualize._visSteering(0.99) + " 0.99")

    print("=== Steering test end ===")

def testAccel():
    print("=== Accelerometer test ===")
    print(visualize._visAccel(0,0,0))
    print(visualize._visAccel(10,0,0))
    print(visualize._visAccel(20,0,0))
    print(visualize._visAccel(30,0,0))
    print(visualize._visAccel(0,10,0))
    print(visualize._visAccel(0,20,0))
    print(visualize._visAccel(0,30,0))
    print(visualize._visAccel(10,10,0))
    print(visualize._visAccel(20,20,0))
    print(visualize._visAccel(30,30,0))
    print("=== Accelerometer test end ===")

if __name__ == "__main__":
    testSteering()
    #testAccel()
    